#!/bin/bash
if [ "$STEP" = "step0_repl" ]; then
	exec python3 -O "$(dirname $0)/step0_repl.py" "${@}"
elif [ "$STEP" = "step1_read_print" ]; then
	exec python3 -O "$(dirname $0)/step1_read_print.py" "${@}"	
else
	exec python3 -O "$(dirname $0)/stepA_mal.py" "${@}"
fi
#exec python3 -O "$(dirname $0)/${STEP:-stepA_mal}.py" "${@}"
